environment: dev
replicas_min: 1
replicas_max: 1
cpu: 200m
memory: 1000Mi
db_tier: db-f1-micro
db_highAvailability: false
db_pointInTimeRecovery: false
kafka_schema_registry: kafka-schema-registry.nais-q.adeo.no
env:
  SPRING_PROFILES_ACTIVE: default
  SKRIVEMODUS: READWRITE
  KAFKA_SCHEMA_REGISTRY: https://kafka-schema-registry.nais-q.adeo.no
