environment: dev
replicas_min: 1
replicas_max: 1
cpu: 700m
memory: 4000Mi
db_tier: db-f1-micro
db_highAvailability: false
db_pointInTimeRecovery: false
env:
  SPRING_PROFILES_ACTIVE: default
  SKRIVEMODUS: READWRITE
