environment: dev
replicas_min: 1
replicas_max: 1
cpu: 100m
memory: 600Mi
db_tier: db-f1-micro
db_highAvailability: false
db_pointInTimeRecovery: false
schema_registry_url: kafka-schema-registry.nais-q.adeo.no
env:
  SPRING_PROFILES_ACTIVE: default
  SKRIVEMODUS: READWRITE
