apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-identer-cache
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/liveness
  readiness:
    path: /internal/health/readiness
  startup:
    path: /internal/health/liveness
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  tokenx:
    enabled: true
  azure:
    application:
      tenant: nav.no
      enabled: true
      allowAllUsers: false
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        diskSize: 10
        highAvailability: {{db_highAvailability}}
        pointInTimeRecovery: {{db_pointInTimeRecovery}}
        diskAutoresize: true
        databases:
          - name: flex-identer-cache-db
            envVarPrefix: DATABASE
            users:
              - name: bigquery-dataprodukt
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  accessPolicy:
    inbound:
      rules:
        - application: sykepengesoknad
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
