name: workflow
on:
  workflow_dispatch:
  push:

jobs:
  felles-workflow:
    timeout-minutes: 10
    uses: navikt/flex-github-actions-workflows/.github/workflows/spring-boot.yml@main
    permissions:
      packages: read
      contents: read
      actions: read
      id-token: write
      security-events: write
    with:
      app: ${{ github.event.repository.name }}
    secrets: inherit
